# Generated by Django 6.1 on 2026-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='started_at',
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('art', 'Art'), ('writing', 'Writing'), ('baking', 'Baking')], default='programming', max_length=20),
        ),
    ]
