# Generated by Django 6.1 on 2026-09-21 13:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_skills_ended_at_remove_skills_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('project_url', models.URLField(help_text='Link to itch.io or external site')),
                ('image_url', models.URLField(help_text='Link to thumbnail image')),
            ],
        ),
    ]
